config/routes.rb
Rails.application.routes.draw do
  resources :livres
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/livre.rb
class Livre < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/livres_controller.rb
class LivresController < ApplicationController
  before_action :set_livre, only: %i[ show edit update destroy ]

  # GET /livres or /livres.json
  def index
    @livres = Livre.all
  end

  # GET /livres/1 or /livres/1.json
  def show
  end

  # GET /livres/new
  def new
    @livre = Livre.new
  end

  # GET /livres/1/edit
  def edit
  end

  # POST /livres or /livres.json
  def create
    @livre = Livre.new(livre_params)

    respond_to do |format|
      if @livre.save
        format.html { redirect_to @livre, notice: "Livre was successfully created." }
        format.json { render :show, status: :created, location: @livre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @livre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livres/1 or /livres/1.json
  def update
    respond_to do |format|
      if @livre.update(livre_params)
        format.html { redirect_to @livre, notice: "Livre was successfully updated." }
        format.json { render :show, status: :ok, location: @livre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livres/1 or /livres/1.json
  def destroy
    @livre.destroy!

    respond_to do |format|
      format.html { redirect_to livres_path, status: :see_other, notice: "Livre was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livre
      @livre = Livre.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def livre_params
      params.expect(livre: [ :titre, :auteur, :resume, :date ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/livres_helper.rb
module LivresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bookio" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/livres/_form.html.erb
<%= simple_form_for(@livre) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :titre %>
    <%= f.input :auteur %>
    <%= f.input :resume %>
    <%= f.input :date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/livres/_livre.html.erb
<div id="<%= dom_id livre %>">
  <p>
    <strong>Titre:</strong>
    <%= livre.titre %>
  </p>

  <p>
    <strong>Auteur:</strong>
    <%= livre.auteur %>
  </p>

  <p>
    <strong>Resume:</strong>
    <%= livre.resume %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= livre.date %>
  </p>

</div>

app/views/livres/edit.html.erb
<% content_for :title, "Editing livre" %>

<h1>Editing livre</h1>

<%= render "form", livre: @livre %>

<br>

<div>
  <%= link_to "Show this livre", @livre %> |
  <%= link_to "Back to livres", livres_path %>
</div>

app/views/livres/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Livres" %>

<h1>Livres</h1>

<div id="livres">
  <% @livres.each do |livre| %>
    <%= render livre %>
    <p>
      <%= link_to "Show this livre", livre %>
    </p>
  <% end %>
</div>

<%= link_to "New livre", new_livre_path %>

app/views/livres/new.html.erb
<% content_for :title, "New livre" %>

<h1>New livre</h1>

<%= render "form", livre: @livre %>

<br>

<div>
  <%= link_to "Back to livres", livres_path %>
</div>

app/views/livres/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @livre %>

<div>
  <%= link_to "Edit this livre", edit_livre_path(@livre) %> |
  <%= link_to "Back to livres", livres_path %>

  <%= button_to "Destroy this livre", @livre, method: :delete %>
</div>